"""ATS-safe DOCX rendering.

Both formats ship because ATSes disagree: Workday and Taleo parse .docx more
reliably than PDF, iCIMS and Greenhouse handle PDF fine, and a few older
systems still refuse PDF outright. Generating both costs nothing and removes
the guess.

The same constraints as the PDF, plus two that are specific to Word:
  * no tables -- Word tables are the classic "two column resume" trap, and a
    date column is the usual excuse for adding one. A right-aligned tab stop
    does the same job in one paragraph, which parses as one line of text.
  * no content controls, no text boxes, no headers/footers. Text in a Word
    header is invisible to a large share of parsers, which is exactly where
    people like to put their phone number.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_TAB_ALIGNMENT
from docx.shared import Pt, RGBColor

from .tailor import Plan

_USABLE_WIDTH = Pt(468)     # 6.5in at Letter with 1in margins


def _tight(paragraph, before: float = 0, after: float = 0,
           line: float = 1.0) -> None:
    fmt = paragraph.paragraph_format
    fmt.space_before = Pt(before)
    fmt.space_after = Pt(after)
    fmt.line_spacing = line


def _run(paragraph, text: str, *, bold: bool = False, italic: bool = False,
         size: float = 10, color: tuple[int, int, int] = (40, 40, 40)):
    run = paragraph.add_run(text)
    run.bold = bold
    run.italic = italic
    run.font.size = Pt(size)
    run.font.name = "Calibri"
    run.font.color.rgb = RGBColor(*color)
    return run


def scrub(doc, name: str) -> None:
    """Set the document properties to what is true, before they ship.

    python-docx builds from its own default template, and that template is not
    blank: creator "python-docx", description "generated by python-docx", a
    created date in December 2013, and an <Application> claiming Microsoft
    Macintosh Word. Invisible in the document, one right-click away in file
    properties, and the PDF renderer already ships its properties empty -- so
    the .docx should not be the file that talks.
    """
    props = doc.core_properties
    props.author = name
    props.last_modified_by = name
    props.title = props.subject = props.comments = ""
    props.category = props.keywords = ""
    props.created = props.modified = datetime.now()
    props.revision = 1

    # app.xml is not exposed by python-docx, so it is patched in place. The
    # elements are emptied rather than rewritten: claiming to be a Word build
    # that never touched this file is worse than claiming nothing.
    try:
        part = next(p for p in doc.part.package.parts
                    if p.partname == "/docProps/app.xml")
        xml = part.blob.decode("utf-8")
        for tag in ("Application", "Company", "Template"):
            xml = re.sub(f"<{tag}>.*?</{tag}>", f"<{tag}></{tag}>", xml)
        part._blob = xml.encode("utf-8")
    except (StopIteration, AttributeError):
        pass


def render(plan: Plan, path: Path) -> Path:
    ident = plan.master.identity
    doc = Document()

    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(10)
    for section in doc.sections:
        section.top_margin = section.bottom_margin = Pt(50)
        section.left_margin = section.right_margin = Pt(54)

    # -- name + contact ---------------------------------------------------
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _tight(p, after=2)
    _run(p, ident["name"], bold=True, size=20, color=(20, 20, 20))

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _tight(p, after=8)
    contact = "  |  ".join(
        v for v in (ident.get("location"), ident.get("email"),
                    ident.get("phone"), ident.get("linkedin"),
                    ident.get("github")) if v
    )
    _run(p, contact, size=9.5, color=(80, 80, 80))

    def heading(text: str) -> None:
        p = doc.add_paragraph()
        _tight(p, before=8, after=2)
        _run(p, text.upper(), bold=True, size=11, color=(30, 30, 30))
        # A bottom border on the paragraph, not a drawn line or a table row --
        # it renders as a rule and parses as nothing.
        pPr = p._p.get_or_add_pPr()
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
        borders = OxmlElement("w:pBdr")
        bottom = OxmlElement("w:bottom")
        bottom.set(qn("w:val"), "single")
        bottom.set(qn("w:sz"), "6")
        bottom.set(qn("w:space"), "1")
        bottom.set(qn("w:color"), "323232")
        borders.append(bottom)
        pPr.append(borders)

    def bullet(text: str) -> None:
        p = doc.add_paragraph()
        _tight(p, after=2)
        p.paragraph_format.left_indent = Pt(18)
        p.paragraph_format.first_line_indent = Pt(-9)
        _run(p, "- " + text, size=10)

    # -- summary ----------------------------------------------------------
    if plan.summary:
        heading("Summary")
        p = doc.add_paragraph()
        _tight(p, after=4)
        _run(p, plan.summary)

    # -- education --------------------------------------------------------
    heading("Education")
    coursework = ", ".join(c.name for c in plan.coursework)
    for i, edu in enumerate(plan.master.education):
        p = doc.add_paragraph()
        _tight(p)
        _run(p, edu.degree, bold=True, size=10.5, color=(30, 30, 30))
        p = doc.add_paragraph()
        _tight(p, after=2)
        _run(p, edu.school, italic=True, size=10, color=(80, 80, 80))
        if i == 0 and coursework:
            p = doc.add_paragraph()
            _tight(p, after=4)
            p.paragraph_format.left_indent = Pt(10)
            _run(p, f"Relevant Coursework: {coursework}", size=9,
                 color=(60, 60, 60))

    # -- skills -----------------------------------------------------------
    heading("Skills")
    for category, items in plan.skills:
        p = doc.add_paragraph()
        _tight(p, after=2)
        _run(p, f"{category}: ", bold=True, size=10, color=(30, 30, 30))
        _run(p, ", ".join(items), size=10, color=(50, 50, 50))

    # -- experience -------------------------------------------------------
    heading("Experience")
    for section in plan.experience:
        entry = section.entry
        p = doc.add_paragraph()
        _tight(p, before=4)
        p.paragraph_format.tab_stops.add_tab_stop(
            _USABLE_WIDTH, WD_TAB_ALIGNMENT.RIGHT
        )
        _run(p, entry.title, bold=True, size=10.5, color=(30, 30, 30))
        _run(p, "\t" + entry.dates, size=9.5, color=(100, 100, 100))

        p = doc.add_paragraph()
        _tight(p, after=2)
        org = f"{entry.company} - {entry.location}" if entry.location else entry.company
        _run(p, org, italic=True, size=10, color=(80, 80, 80))

        for chosen in section.chosen:
            bullet(chosen.text)

    # -- projects ---------------------------------------------------------
    if plan.projects:
        heading("Projects")
        for section in plan.projects:
            p = doc.add_paragraph()
            _tight(p, before=4, after=2)
            _run(p, section.entry.name, bold=True, size=10.5, color=(30, 30, 30))
            for chosen in section.chosen:
                bullet(chosen.text)

    scrub(doc, ident["name"])
    path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(path))
    return path
